#!/bin/sh
alias j='z'
alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# alias lvim='nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"'

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Remarkable
alias remarkable_ssh='ssh root@10.11.99.1'
alias restream='restream -p'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

alias mach_java_mode="export SDKMAN_DIR="$HOME/.sdkman" && [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh""

#Monitors Controls
alias dm_L_HDMI="xrandr --output eDP1 --primary --mode 1366x768  --output HDMI1 --mode 1920x1080 --rate 60.00 --right-of eDP1"
alias dm_L_HDMI_switch="xrandr --output eDP1 --primary --mode 1366x768  --output HDMI1 --mode 1920x1080 --rate 60.00 --left-of eDP1"

alias dm_HDMI_VGA="xrandr --output HDMI1 --primary --mode 1920x1080 --output DP2 --mode 1366x768 --left-of HDMI1"
alias dm_HDMI_VGA_switch="xrandr --output HDMI1 --primary --mode 1920x1080 --output DP2 --mode 1366x768 --right-of HDMI1"

alias sm_HDMI="xrandr --output HDMI1 --primary --mode 1920x1080 --output DP2 --off --output eDP1 --off"
alias sm_lap="xrandr --output eDP1 --primary --mode 1366x768 --output DP2 --off --output HDMI1 --off"

alias dm_dup_VGA_HD="xrandr --output eDP1 --primary --mode 1366x768 --output DP2 --mode 1366x768 --same-as eDP1"
alias dm_dup_HDMI_HD="xrandr --output eDP1 --primary --mode 1366x768 --output HDMI1 --mode 1366x768 --same-as eDP1"

alias dm_dup_VGA_FHD="xrandr --output eDP1 --primary --mode 1366x768 --output DP2 --mode 1920x1080 --same-as eDP1"
alias dm_dup_HDMI_FHD="xrandr --output eDP1 --primary --mode 1366x768 --output HDMI1 --mode 1920x1080 --same-as eDP1"

alias tm="xrandr --output HDMI1 --primary --mode 1920x1080 --output eDP1 --mode 1366x768 --right-of HDMI1 --output DP2 --mode 1366x768 --left-of HDMI1"
#Done

alias sumount "sudo mount -t auto /dev/sdc1 ./Documents/Ex_Drive/"
# Editor
alias r="ranger"
alias emacs="emacsclient -nw -c -a 'emacs'"
alias m="git checkout master"
alias s="git checkout stable"
alias re="refresh_emacs"
alias nvim="neovidecloseterminal"


alias n="nnn -a -H -e -A -c"
# alias n="nnn -dHeAa"
alias N="sudo nnn -e -d -A -c -a"

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
